### ISSUE TITLE
Error: Can't set headers after they are sent.

### ISSUE THREAD

**Issue by eddyekofo94** [Atinux/vue-adonis#9]
```
Error: Can't set headers after they are sent.
    at validateHeader (_http_outgoing.js:504:11)
    at ServerResponse.setHeader (_http_outgoing.js:511:3)
    at Object.Response.header (/Users/eddyekofo/Coding/WebDev/Nodejs/Adonisjs/adonis-vue/node_modules/node-res/src/Response/index.js:52:7)
    at Object.Response.send (/Users/eddyekofo/Coding/WebDev/Nodejs/Adonisjs/adonis-vue/node_modules/node-res/src/Response/index.js:159:14)
    at Response.send (/Users/eddyekofo/Coding/WebDev/Nodejs/Adonisjs/adonis-vue/node_modules/adonis-framework/src/Response/index.js:177:13)
    at Response.sendView (/Users/eddyekofo/Coding/WebDev/Nodejs/Adonisjs/adonis-vue/node_modules/adonis-framework/src/Response/index.js:122:10)
    at sendView.next (<anonymous>)
    at onFulfilled (/Users/eddyekofo/Coding/WebDev/Nodejs/Adonisjs/adonis-vue/node_modules/co/index.js:65:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)

```

**Comment by jesusvallez** [comment]
Same problem and @Atinux does not reply us.
It seems that the project is abandoned

**Comment by atinux** [comment]
It is not, I just cannot manage all issues, the template has been updated. So please look at the code changes.
